import type { RuleBankRuleInput } from "@/lib/rules/types";

export const STARTER_RULES: RuleBankRuleInput[] = [
  {
    id: "starter-fact-no-invented-claims",
    title: "Do not invent fragile claims",
    body: "Do not invent metrics, customers, dates, quotes, roadmap timing, hidden mechanisms, motives, or factual claims.",
    category: "fact_discipline",
    mode: "hard_constraint",
    source: "starter",
    scope: "global",
    targetJson: ["skill_rules", "linguistic_rules"],
    payloadJson: { confidence: 94, appliesTo: ["all"] },
    enabled: true,
  },
  {
    id: "starter-fact-causal-restraint",
    title: "Use restrained causal language",
    body: "Do not claim that one change caused, drove, proved, or explained another unless the supplied context supports that relationship.",
    category: "fact_discipline",
    mode: "hard_constraint",
    source: "starter",
    scope: "global",
    targetJson: ["skill_rules", "linguistic_rules"],
    payloadJson: { confidence: 90, appliesTo: ["all"] },
    enabled: true,
  },
  {
    id: "starter-specificity-concrete-anchor",
    title: "Add a concrete anchor",
    body: "Each substantial paragraph or draft should carry a concrete noun, checkable detail, observed consequence, direct quote, or specific example.",
    category: "specificity",
    mode: "guidance",
    source: "starter",
    scope: "global",
    targetJson: ["skill_rules"],
    payloadJson: { confidence: 82, appliesTo: ["all"] },
    enabled: true,
  },
  {
    id: "starter-specificity-no-theater",
    title: "Avoid specificity theater",
    body: "Prefer fewer verified facts to many decorative details. Cut suspiciously exact claims, synthetic milestone names, and unsupported quotes.",
    category: "specificity",
    mode: "guidance",
    source: "starter",
    scope: "global",
    targetJson: ["skill_rules", "linguistic_rules"],
    payloadJson: { confidence: 84, appliesTo: ["all"] },
    enabled: true,
  },
  {
    id: "starter-format-match-medium",
    title: "Match format to medium",
    body: "Use structure when the medium benefits from scanning, and use running prose when casual replies, comments, DMs, or forum posts do not need lists.",
    category: "format_fit",
    mode: "guidance",
    source: "starter",
    scope: "global",
    targetJson: ["skill_rules"],
    payloadJson: { confidence: 78, appliesTo: ["all"] },
    enabled: true,
  },
  {
    id: "starter-accessibility-preserve-structure",
    title: "Preserve useful accessibility structure",
    body: "Do not remove useful headings, lists, descriptive links, citations, caveats, or next steps when the medium requires them.",
    category: "accessibility",
    mode: "guidance",
    source: "starter",
    scope: "global",
    targetJson: ["skill_rules"],
    payloadJson: { confidence: 82, appliesTo: ["all"] },
    enabled: true,
  },
  {
    id: "starter-plain-language-verbs",
    title: "Prefer plain verbs",
    body: "Prefer plain words, ordinary repetition, and active verbs over abstract noun phrases and synonym-chasing.",
    category: "plain_language",
    mode: "guidance",
    source: "starter",
    scope: "global",
    targetJson: ["skill_rules"],
    payloadJson: { confidence: 78, appliesTo: ["all"] },
    enabled: true,
  },
  {
    id: "starter-regularity-break-repeated-moves",
    title: "Break repeated visible patterns",
    body: "Watch for repeated three-part cadence, identical paragraph arcs, repeated concession rhythm, and the same punctuation move across consecutive paragraphs.",
    category: "regularity",
    mode: "guidance",
    source: "starter",
    scope: "global",
    targetJson: ["skill_rules"],
    payloadJson: { confidence: 80, appliesTo: ["all"] },
    enabled: true,
  },
  {
    id: "starter-regularity-em-dash-casual",
    title: "Limit repeated em dashes in casual prose",
    body: "In casual internet prose, prefer commas, colons, or full stops over repeated em dashes unless the dash clearly earns its keep.",
    category: "regularity",
    mode: "hard_constraint",
    source: "starter",
    scope: "global",
    targetJson: ["skill_rules", "linguistic_rules", "avoided_phrases", "retrieval_avoid_vocabulary"],
    payloadJson: { phrases: ["—"], confidence: 90, appliesTo: ["all"] },
    enabled: true,
  },
  {
    id: "starter-formula-phrases",
    title: "Avoid formula phrases",
    body: "Avoid common formula phrases unless the surrounding context makes the phrase specifically useful.",
    category: "formula_phrases",
    mode: "banned_phrase",
    source: "starter",
    scope: "global",
    targetJson: ["avoided_phrases", "retrieval_avoid_vocabulary", "skill_rules"],
    payloadJson: {
      confidence: 90,
      phrases: [
        "it's important to note",
        "it's worth noting",
        "when it comes to",
        "in conclusion",
        "in today's fast-paced world",
        "ever-evolving landscape",
        "at the end of the day",
        "dive deep into",
        "embark on a journey",
        "is a testament to",
        "plays a key role",
        "plays a pivotal role",
      ],
      appliesTo: ["all"],
    },
    enabled: true,
  },
  {
    id: "starter-formula-jargon",
    title: "Avoid default model jargon",
    body: "Avoid fallback diction such as leverage, harness, foster, empower, unlock, unveil, robust, seamless, holistic, and valuable insights unless it is the right literal word.",
    category: "formula_phrases",
    mode: "banned_phrase",
    source: "starter",
    scope: "global",
    targetJson: ["avoided_phrases", "retrieval_avoid_vocabulary", "skill_rules"],
    payloadJson: {
      confidence: 88,
      phrases: ["leverage", "harness", "foster", "empower", "unlock", "unveil", "robust", "seamless", "holistic", "valuable insights"],
      appliesTo: ["all"],
    },
    enabled: true,
  },
  {
    id: "starter-stance-match-genre",
    title: "Match stance to genre",
    body: "Use visible stance for reviews, opinion, replies, and personal posts. Keep summaries, documentation, and reporting neutral unless the user asks for a view.",
    category: "stance_voice",
    mode: "guidance",
    source: "starter",
    scope: "global",
    targetJson: ["skill_rules"],
    payloadJson: { confidence: 78, appliesTo: ["all"] },
    enabled: true,
  },
  {
    id: "starter-no-fake-human-mess",
    title: "Do not fake human messiness",
    body: "Do not add typos, forced slang, staged uncertainty, random fragments, fake profanity, or artificial sentence-length wobble to simulate humanity.",
    category: "regularity",
    mode: "hard_constraint",
    source: "starter",
    scope: "global",
    targetJson: ["skill_rules", "linguistic_rules"],
    payloadJson: { confidence: 92, appliesTo: ["all"] },
    enabled: true,
  },
  {
    id: "starter-provenance-high-stakes",
    title: "Use provenance for authorship claims",
    body: "When authorship matters, use draft history, revision history, citations, notes, outlines, source traces, and disclosed AI use rather than surface style.",
    category: "provenance",
    mode: "guidance",
    source: "starter",
    scope: "global",
    targetJson: ["skill_rules"],
    payloadJson: { confidence: 76, appliesTo: ["all"] },
    enabled: true,
  },
];
